# Generated by Django 4.2.1 on 2023-05-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_task_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.CharField(default='default_author', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='department',
            field=models.CharField(default='default_department', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='subject',
            field=models.CharField(default='default_subject', max_length=50),
        ),
    ]
