# Generated by Django 4.2.1 on 2023-05-22 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_user_f_remove_user_i_remove_user_o_user_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'student'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
