# Generated by Django 4.2.1 on 2023-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='type',
            field=models.CharField(choices=[('passport', 'Passport'), ('vzaim', 'Vzaim')], default='passport', max_length=20),
        ),
    ]
