# Generated by Django 4.2.1 on 2023-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userfiles_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('academy', 'Academ'), ('method', 'Method'), ('treat', 'Treat')], default='academy', max_length=20),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='type',
            field=models.CharField(choices=[('passport', 'Passport'), ('vzaim', 'Vzaim'), ('collective', 'Collective'), ('working', 'Working')], default='passport', max_length=20),
        ),
    ]
